### ISSUE TITLE
deploy script generates incorrect audit_log_view 

### ISSUE THREAD

**Issue by pietmolenaar** [ioncache/DBIx-Class-AuditLog#20]
When running the deployment script column values are apparently shifted: the view below was produced. This was win7 mysql 5.5.

/*View: audit_log_view*/
------------------------

/*Column Information*/
----------------------

Field         Type          Collation          Null    Key     Default              Extra   Privileges                       Comment  
------------  ------------  -----------------  ------  ------  -------------------  ------  -------------------------------  ---------
change_id     int(11)       (NULL)             NO              0                            select,insert,update,references           
changeset_id  varchar(255)  latin1_swedish_ci  YES             (NULL)                       select,insert,update,references           
old_value     varchar(255)  latin1_swedish_ci  YES             (NULL)                       select,insert,update,references           
new_value     varchar(10)   latin1_swedish_ci  NO              (NULL)                       select,insert,update,references           
action_type   varchar(255)  latin1_swedish_ci  NO              (NULL)                       select,insert,update,references           
audited_row   int(11)       (NULL)             NO              0                            select,insert,update,references           
table_name    varchar(255)  latin1_swedish_ci  YES             (NULL)                       select,insert,update,references           
field_name    timestamp     (NULL)             NO              0000-00-00 00:00:00          select,insert,update,references           
description   varchar(40)   latin1_swedish_ci  NO              (NULL)                       select,insert,update,references           
created_on    varchar(40)   latin1_swedish_ci  NO              (NULL)                       select,insert,update,references           
user_name     varchar(100)  latin1_swedish_ci  YES             (NULL)                       select,insert,update,references           

/*DDL Information*/
-------------------

CREATE ALGORITHM=UNDEFINED DEFINER=`ogtool_admin`@`%` SQL SECURITY DEFINER VIEW `audit_log_view` AS 
select
  `c`.`id`          AS `change_id`,
  `c`.`old_value`   AS `changeset_id`,
  `c`.`new_value`   AS `old_value`,
  `a`.`action_type` AS `new_value`,
  `a`.`audited_row` AS `action_type`,
  `s`.`id`          AS `audited_row`,
  `s`.`description` AS `table_name`,
  `s`.`created_on`  AS `field_name`,
  `t`.`name`        AS `description`,
  `f`.`name`        AS `created_on`,
  `u`.`name`        AS `user_name`
from (((((`audit_log_action` `a`
       join `audit_log_change` `c`
         on ((`c`.`action_id` = `a`.`id`)))
      join `audit_log_field` `f`
        on ((`f`.`id` = `c`.`field_id`)))
     join `audit_log_table` `t`
       on ((`t`.`id` = `a`.`audited_table_id`)))
    join `audit_log_changeset` `s`
      on ((`s`.`id` = `a`.`changeset_id`)))
   left join `audit_log_user` `u`
     on ((`s`.`user_id` = `u`.`id`)))

**Comment by Getty** [comment]
Fixed in this pull request: https://github.com/ioncache/DBIx-Class-AuditLog/pull/26

**Comment by ioncache** [comment]
fixed in release 0.6.3, released on 2016-08-13
